<a href="https://colab.research.google.com/github/Rashneema/C140-imdb-contentbased-filtering/blob/main/C140_movie_recommendation_content_based_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.9.24)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [ ]:
from google.colab import files
files.upload()

{}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle

!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

tmdb-movie-metadata.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
!unzip tmdb-movie-metadata.zip

Archive:  tmdb-movie-metadata.zip
replace tmdb_5000_credits.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace tmdb_5000_movies.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

**S.A starts here**

In [ ]:
import pandas as pd
df1=pd.read_csv("tmdb_5000_credits.csv")
df2=pd.read_csv("tmdb_5000_movies.csv")

In [ ]:
df1.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df1.columns=['id','title','cast','crew']

In [ ]:
df2 = df2.merge(df1,on='id')
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

**C139 STARTS HERE**

Formula to calculate weighted movie rating avg

(v/(v+m))*R)+((m/(v+m))*C)

In [ ]:
c=df2["vote_average"].mean()
c

6.092171559442016

In [ ]:
m=df2['vote_count'].quantile(0.9)
m

1838.4000000000015

In [ ]:
q_movies = df2[df2['vote_count']>=m]
q_movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4291,1200000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 9648, ""n...",NaN,176,"[{""id"": 1366, ""name"": ""shotgun""}, {""id"": 13000...",en,Saw,Obsessed with teaching his victims the value o...,63.655973,"[{""name"": ""Lions Gate Films"", ""id"": 35}, {""nam...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Live or die. Make your choice.,Saw,7.2,2184,Saw,"[{""cast_id"": 4, ""character"": ""Dr. Lawrence Gor...","[{""credit_id"": ""52fe4223c3a36847f8006c57"", ""de..."
4300,1200000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name...",NaN,500,"[{""id"": 2052, ""name"": ""traitor""}, {""id"": 6099,...",en,Reservoir Dogs,A botched robbery indicates a police informant...,66.925866,"[{""name"": ""Live Entertainment"", ""id"": 285}, {""...",...,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Every dog has his day.,Reservoir Dogs,8.0,3697,Reservoir Dogs,"[{""cast_id"": 20, ""character"": ""Mr. White/Larry...","[{""credit_id"": ""52fe424ac3a36847f8012cb9"", ""de..."
4302,1200000,"[{""id"": 37, ""name"": ""Western""}]","http://www.mgm.com/#/our-titles/766/The-Good,-...",429,"[{""id"": 801, ""name"": ""bounty hunter""}, {""id"": ...",it,"Il buono, il brutto, il cattivo",While the Civil War rages between the Union an...,88.377076,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...",...,161.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}]",Released,For three men the Civil War wasn't hell. It wa...,"The Good, the Bad and the Ugly",8.1,2311,"The Good, the Bad and the Ugly","[{""cast_id"": 6, ""character"": ""Tuco"", ""credit_i...","[{""credit_id"": ""575aee00c3a3682d10000281"", ""de..."
4337,1300000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,103,"[{""id"": 422, ""name"": ""vietnam veteran""}, {""id""...",en,Taxi Driver,A mentally unstable Vietnam War veteran works ...,58.845025,"[{""name"": ""Columbia Pictures Corporation"", ""id...",...,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"On every street in every city, there's a nobod...",Taxi Driver,8.0,2535,Taxi Driver,"[{""cast_id"": 5, ""character"": ""Travis Bickle"", ...","[{""credit_id"": ""52fe4218c3a36847f8003803"", ""de..."
4602,350000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,389,"[{""id"": 934, ""name"": ""judge""}, {""id"": 1417, ""n...",en,12 Angry Men,The defense and the prosecution have rested an...,59.259204,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...",...,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Life is in their hands. Death is on their minds.,12 Angry Men,8.2,2078,12 Angry Men,"[{""cast_id"": 29, ""character"": ""Juror 8"", ""cred...","[{""credit_id"": ""52fe423dc3a36847f800ec55"", ""de..."

In [ ]:
q_movies.shape

(481, 23)

In [ ]:
#function to calculate the metric score
def weighted_rating(x,m=m,c=c): #x is each row
  v=x["vote_count"]
  r=x['vote_average']
  score = (v/(v+m)*r) + (m/(m+v)*c)
  return score

In [ ]:
#Applying function on each row
q_movies['score']=q_movies.apply(weighted_rating,axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
q_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.050669
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.665696
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.239396
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.346721
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.096368

In [ ]:
#sorting the dataframe by score and displaying only selected columns 
q_movies = q_movies.sort_values('score',ascending=False)
q_movies[['title_x','vote_count','vote_average','score']].head(10)

,title_x,vote_count,vote_average,score
1881,The Shawshank Redemption,8205,8.5,8.059258
662,Fight Club,9413,8.3,7.939256
65,The Dark Knight,12002,8.2,7.920020
3232,Pulp Fiction,8428,8.3,7.904645
96,Inception,13752,8.1,7.863239
3337,The Godfather,5893,8.4,7.851236
95,Interstellar,10867,8.1,7.809479
809,Forrest Gump,7927,8.2,7.803188
329,The Lord of the Rings: The Return of the King,8064,8.1,7.727243
1990,The Empire Strikes Back,5879,8.2,7.697884

In [ ]:
import plotly.express as px
fig=px.bar(q_movies.head(10),x='score',y='title_x')
fig.show()

**CLASS 140 STARTS HERE**

**CONTENT BASED FILTERING**

In [ ]:
df2[['title_x', 'cast', 'crew', 'keywords', 'genres']].head(3)

,title_x,cast,crew,keywords,genres
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [ ]:
from ast import literal_eval

features = ['cast', 'crew', 'keywords', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(literal_eval)

df2.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title_x                  object
vote_average            float64
vote_count                int64
title_y                  object
cast                     object
crew                     object
dtype: object

**S.A starts here**

In [ ]:
df2['crew'][0]

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [ ]:
import numpy as np
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
    return np.nan

df2['director'] = df2['crew'].apply(get_director)

In [ ]:
df2.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,director
0,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,"[{'id': 1463, 'name': 'culture clash'}, {'id':...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de...",James Cameron

In [ ]:
df2['cast'][0]

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [ ]:
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        return names
    return []

features = ['cast', 'keywords', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(get_list)

In [ ]:
df2.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,director
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{'credit_id': '52fe48009251416c750aca23', 'de...",James Cameron

In [ ]:
df2['cast'][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez',
 'Giovanni Ribisi',
 'Joel David Moore',
 'CCH Pounder',
 'Wes Studi',
 'Laz Alonso',
 'Dileep Rao',
 'Matt Gerald',
 'Sean Anthony Moran',
 'Jason Whyte',
 'Scott Lawrence',
 'Kelly Kilgour',
 'James Patrick Pitt',
 'Sean Patrick Murphy',
 'Peter Dillon',
 'Kevin Dorman',
 'Kelson Henderson',
 'David Van Horn',
 'Jacob Tomuri',
 'Michael Blain-Rozgay',
 'Jon Curry',
 'Luke Hawker',
 'Woody Schultz',
 'Peter Mensah',
 'Sonia Yee',
 'Jahnel Curfman',
 'Ilram Choi',
 'Kyla Warren',
 'Lisa Roumain',
 'Debra Wilson',
 'Chris Mala',
 'Taylor Kibby',
 'Jodie Landau',
 'Julie Lamm',
 'Cullen B. Madden',
 'Joseph Brady Madden',
 'Frankie Torres',
 'Austin Wilson',
 'Sara Wilson',
 'Tamica Washington-Miller',
 'Lucy Briant',
 'Nathan Meister',
 'Gerry Blair',
 'Matthew Chamberlain',
 'Paul Yates',
 'Wray Wilson',
 'James Gaylyn',
 'Melvin Leno Clark III',
 'Carvon Futrell',
 'Brandon Jelkes',
 'Micah Moch',
 'Hanniyah Muhammad',
 'Christopher Nolen',
 'Christa Oliver',
 'April Marie Thomas',
 'Bravita A. Threatt',
 'Colin Bleasdale',
 'Mike Bodnar',
 'Matt Clayton',
 'Nicole Dionne',
 'Jamie Harrison',
 'Allan Henry',
 'Anthony Ingruber',
 'Ashley Jeffery',
 'Dean Knowsley',
 'Joseph Mika-Hunt',
 'Terry Notary',
 'Kai Pantano',
 'Logan Pithyou',
 'Stuart Pollock',
 'Raja',
 'Gareth Ruck',
 'Rhian Sheehan',
 'T. J. Storm',
 'Jodie Taylor',
 'Alicia Vela-Bailey',
 'Richard Whiteside',
 'Nikie Zambo',
 'Julene Renee']

In [ ]:
df2[['title_x', 'cast', 'director', 'keywords', 'genres']].head(3)

,title_x,cast,director,keywords,genres
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",James Cameron,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",Gore Verbinski,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Sam Mendes,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]"

In [ ]:
def clean_data(x):
    if isinstance(x, list): #checkig if it is a list
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        if isinstance(x, str): #else checking if it is a str
            return str.lower(x.replace(" ", ""))
        else:
            return ''

features = ['cast', 'keywords', 'director', 'genres']
for feature in features:
    df2[feature] = df2[feature].apply(clean_data)

In [ ]:
df2.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,director
0,237000000,"[action, adventure, fantasy, sciencefiction]",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[samworthington, zoesaldana, sigourneyweaver, ...","[{'credit_id': '52fe48009251416c750aca23', 'de...",jamescameron

In [ ]:
def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
df2['soup'] = df2.apply(create_soup, axis=1)

In [ ]:
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,director,soup
0,237000000,"[action, adventure, fantasy, sciencefiction]",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[samworthington, zoesaldana, sigourneyweaver, ...","[{'credit_id': '52fe48009251416c750aca23', 'de...",jamescameron,cultureclash future spacewar spacecolony socie...
1,300000000,"[adventure, fantasy, action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[johnnydepp, orlandobloom, keiraknightley, ste...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...",goreverbinski,ocean drugabuse exoticisland eastindiatradingc...
2,245000000,"[action, adventure, crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[danielcraig, christophwaltz, léaseydoux, ralp...","[{'credit_id': '54805967c3a36829b5002c41', 'de...",sammendes,spy basedonnovel secretagent sequel mi6 britis...
3,250000000,"[action, crime, drama, thriller]",http://www.thedarkknightrises.com/,49026,"[dccomics, crimefighter, terrorist, secretiden...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[christianbale, michaelcaine, garyoldman, anne...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...",christophernolan,dccomics crimefighter terrorist secretidentity...
4,260000000,"[action, adventure, sciencefiction]",http://movies.disney.com/john-carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[taylorkitsch, lynncollins, samanthamorton, wi...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...",andrewstanton,basedonnovel mars medallion spacetravel prince...

**Better copy paste these codes to the student depending on the time**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(df2['soup'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
df2 = df2.reset_index()
indices = pd.Series(df2.index, index=df2['title_x'])

In [ ]:
df2.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew,director,soup
0,0,237000000,"[action, adventure, fantasy, sciencefiction]",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[samworthington, zoesaldana, sigourneyweaver, ...","[{'credit_id': '52fe48009251416c750aca23', 'de...",jamescameron,cultureclash future spacewar spacecolony socie...
1,1,300000000,"[adventure, fantasy, action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[johnnydepp, orlandobloom, keiraknightley, ste...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...",goreverbinski,ocean drugabuse exoticisland eastindiatradingc...
2,2,245000000,"[action, adventure, crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[danielcraig, christophwaltz, léaseydoux, ralp...","[{'credit_id': '54805967c3a36829b5002c41', 'de...",sammendes,spy basedonnovel secretagent sequel mi6 britis...
3,3,250000000,"[action, crime, drama, thriller]",http://www.thedarkknightrises.com/,49026,"[dccomics, crimefighter, terrorist, secretiden...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[christianbale, michaelcaine, garyoldman, anne...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...",christophernolan,dccomics crimefighter terrorist secretidentity...
4,4,260000000,"[action, adventure, sciencefiction]",http://movies.disney.com/john-carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[taylorkitsch, lynncollins, samanthamorton, wi...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...",andrewstanton,basedonnovel mars medallion spacetravel prince...

In [ ]:
def get_recommendations(title, cosine_sim):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return df2['title_x'].iloc[movie_indices]

In [ ]:
get_recommendations('Fight Club', cosine_sim2)

1553                       Se7en
946                     The Game
421                       Zodiac
4564    Straight Out of Brooklyn
45                   World War Z
4462          The Young Unknowns
3863                      August
3043            End of the Spear
1010                  Panic Room
4101                Full Frontal
Name: title_x, dtype: object

In [ ]:
get_recommendations('The Shawshank Redemption', cosine_sim2)

4638    Amidst the Devil's Wings
690               The Green Mile
4408              Jimmy and Judy
1247             City By The Sea
4502               Water & Power
4529           Hurricane Streets
559                 The Majestic
1752              Kiss the Girls
2818                     Witness
4564    Straight Out of Brooklyn
Name: title_x, dtype: object

In [ ]:
get_recommendations('The Godfather', cosine_sim2)

2731      The Godfather: Part II
867      The Godfather: Part III
4638    Amidst the Devil's Wings
4209            The Conversation
3293                 10th & Wolf
2255                   The Yards
1394               Donnie Brasco
3012               The Outsiders
4124          This Thing of Ours
1018             The Cotton Club
Name: title_x, dtype: object